


name: gy7709env

channels:

  - conda-forge

dependencies:

  - boto3

  - botocore

  - gdal

  - geopandas

  - geoplot

  - git

  - imageio

  - joblib

  - jupyter

  - matplotlib

  - netCDF4

  - numpy

  - pandas

  - pip

  - proj4

  - pytest

  - python

  - python-fmask

  - requests

  - rpy2==2.9.4

  - scikit-image

  - scikit-learn

  - scipy

  - setuptools

  - statsmodels

  - pip:

    - copy

    - os

    - osgeo

    - random

    - shutil

    - subprocess

    - time

    - skimage

    - sys

    - warnings

    - geojson

    - google-cloud

    - sentinelhub

    - sentinelsat

    - tenacity

    - tqdm


